app:
  menus:
    - title: title1
      name: name1
      path: path1
    - title: title2
      name: name2
      path: path2
  person:
    name: zhang
    age: 18


management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 15s
  http:
    encoding:
      charset: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  datasource:
    url: jdbc:postgresql://127.0.0.1/rabbit
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

